// HealthSenseKiosk/src/lib/pages/login.svelte
<script lang="ts">
  import { fade, slide, scale } from 'svelte/transition';
  import { supabase } from './supabaseClient'; // Ensure this path is correct
  import fingerprintIcon from '../../assets/fingerprint-svgrepo-com.svg';

  export let onBack: () => void;
  export let onLogin: (user: any) => void; // Pass the user data back
  export let onCreateAccount: () => void;

  let username = ""; // User types: joy.arenas
  let password = "";
  let focusedField: 'username' | 'password' | 'recoveryEmail' | null = null;
  let showFingerprintModal = false;
  let showPassword = false;
  let isCaps = true;
  let isSubmitting = false; 
  let recoveryEmail = "";

  const rows = {
    numbers: ['1','2','3','4','5','6','7','8','9','0'],
    letters: [
      ['Q','W','E','R','T','Y','U','I','O','P'],
      ['A','S','D','F','G','H','J','K','L'],
      ['Z','X','C','V','B','N','M']
    ]
  };

  function handleKeyPress(key: string) {
    if (!focusedField) return;
    const char = isCaps ? key.toUpperCase() : key.toLowerCase();
    if (focusedField === 'username') username += char;
    if (focusedField === 'password') password += char;
  }

  function backspace() {
    if (focusedField === 'username') username = username.slice(0, -1);
    if (focusedField === 'password') password = password.slice(0, -1);
  }

  function toggleFingerprint() { showFingerprintModal = true; }
  function closeFingerprint() { 
    showFingerprintModal = false; 
    scanStatus = 'idle';
  }

  // --- BIOMETRIC SCAN SIMULATION ---
  let scanStatus: 'scanning' | 'success' | 'idle' = 'idle';

  function simulateScan() {
    if (scanStatus !== 'idle') return;
    scanStatus = 'scanning';
    
    setTimeout(() => {
      scanStatus = 'success';
      setTimeout(() => {
        showFingerprintModal = false;
        scanStatus = 'idle';
        // Note: For a real thesis, you'd fetch the last registered user here
        onLogin({ first_name: "Biometric", last_name: "User" }); 
      }, 1000);
    }, 1500);
  }
  
  // --- ACTUAL LOGIN LOGIC ---
 async function handleSignIn() {
    if (!username || !password) {
      alert("Please enter both username and password");
      return;
    }

    isSubmitting = true;

    try {
      const userInput = username.toLowerCase().trim();
      let actualAuthEmail = "";

      // 1. LOOKUP: Check if the user exists in profiles by username
      const { data: profileLookup, error: lookupError } = await supabase
        .from('profiles')
        .select('recovery_email, username')
        .eq('username', userInput)
        .maybeSingle();

      if (profileLookup) {
        // MATCH FOUND: Use recovery_email if it exists, else use .local
        actualAuthEmail = profileLookup.recovery_email 
          ? profileLookup.recovery_email 
          : `${profileLookup.username}@kiosk.local`;
      } else {
        // NO PROFILE FOUND: Maybe they typed a full email or are a .local user?
        // Fallback to your "secretEmail" logic from the web app
        actualAuthEmail = userInput.includes("@") 
          ? userInput 
          : `${userInput}@kiosk.local`;
      }

      // 2. AUTHENTICATE: Sign in with the resolved email
      const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
        email: actualAuthEmail,
        password: password,
      });

      if (authError) throw authError;

      // 3. FETCH FULL PROFILE: Get all data for the Dashboard
      if (authData.user) {
        const { data: profile, error: profileError } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', authData.user.id)
          .single();

        if (profileError) throw profileError;

        // 4. SUCCESS: Pass the profile to the main app state
        onLogin(profile); 
      }
    } catch (err: any) {
      // User-friendly feedback for the touchscreen
      let message = err.message;
      if (err.message === "Invalid login credentials") {
        message = "Access denied. Please check your Patient ID and Password.";
      }
      alert("Login Failed: " + message);
    } finally {
      isSubmitting = false;
    }
  }
</script>

<div 
  class="relative h-full w-full flex flex-col bg-linear-to-b from-[#f0f7ff] to-[#9fc5f8] select-none overflow-hidden"
  on:click={() => focusedField = null}
  role="presentation"
>
  <div class="flex-1 flex flex-col items-center justify-center max-w-lg mx-auto w-full px-6" on:click|stopPropagation role="presentation">
    
    <button on:click={onBack} class="absolute top-16 left-12 text-blue-900/40 font-black tracking-widest text-sm flex items-center gap-2 z-20">
      <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M15 19l-7-7 7-7" />
      </svg>
      BACK
    </button>

    <div class="text-center mb-16">
      <h1 class="text-8xl font-[1000] tracking-tighter leading-none mb-4 uppercase">
        <span class="text-blue-950">LOG</span><span class="text-blue-500">IN</span>
      </h1>
      <p class="text-blue-900/50 font-bold uppercase tracking-[0.2em] text-xs">Access HealthSense Portal</p>
    </div>

    <div class="w-full space-y-6">
      <div class="space-y-2">
        <div class="space-y-2">
          <span class="ml-4 text-[10px] font-black uppercase tracking-widest text-blue-400">Username</span>
          <button 
            type="button"
            on:click|stopPropagation={() => focusedField = 'username'}
            class="relative w-full h-20 px-8 rounded-3xl bg-white border flex items-center text-xl font-bold transition-all outline-none text-left
            {focusedField === 'username' ? 'border-blue-500 ring-4 ring-blue-500/10' : 'border-blue-100 shadow-sm'}"
          >
            <div class="flex items-baseline overflow-hidden w-full">
              <span class="text-blue-900 whitespace-nowrap">{username}</span>
              
              {#if focusedField === 'username'}
                <div class="ml-1 w-0.5 h-6 bg-blue-500 animate-pulse"></div>
              {/if}
              
              {#if !username && focusedField !== 'username'}
                <span class="text-blue-900/20">firstname.lastname</span>
              {/if}
              
              <!-- <span class="ml-1 text-blue-300 font-medium select-none">@kiosk.local</span> -->
            </div>
          </button>
        </div>
      </div>

      <div class="space-y-2">
        <span class="ml-4 text-[10px] font-black uppercase tracking-widest text-blue-400">Password</span>
        
        <div 
          on:click|stopPropagation={() => focusedField = 'password'}
          on:keydown={(e) => e.key === 'Enter' && (focusedField = 'password')}
          role="button"
          tabindex="0"
          class="relative w-full h-20 px-8 rounded-3xl bg-white border flex items-center justify-between text-xl font-bold transition-all outline-none cursor-pointer
          {focusedField === 'password' ? 'border-blue-500 ring-4 ring-blue-500/10' : 'border-blue-100 shadow-sm'}"
        >
          <div class="flex items-center flex-1 h-full pointer-events-none">
            <span class="text-blue-900">
              {password ? (showPassword ? password : '•'.repeat(password.length)) : ''}
              {#if !password && focusedField !== 'password'}
                <span class="text-blue-900/20">••••••••</span>
              {/if}
            </span>
            {#if focusedField === 'password'}
              <div class="ml-1 w-0.5 h-6 bg-blue-500 animate-pulse"></div>
            {/if}
          </div>
          
          <button 
            type="button"
            on:click|stopPropagation={() => showPassword = !showPassword} 
            class="text-blue-900/30 p-2 z-10 hover:text-blue-600 active:scale-90 transition-all"
          >
            {#if showPassword}
              <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.956 9.956 0 0112 5c4.478 0 8.268-2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
              </svg>
            {:else}
              <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268-2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
            {/if}
          </button>
        </div>
      </div>

      <button 
        on:click|stopPropagation={handleSignIn} 
        disabled={isSubmitting}
        class="w-full h-20 bg-blue-950 rounded-3xl text-white font-black text-xl uppercase tracking-widest shadow-xl shadow-blue-900/20 active:scale-[0.98] transition-transform disabled:opacity-50"
      >
        {isSubmitting ? "Verifying..." : "Sign In"}
      </button>
    </div>

    <div class="flex items-center gap-4 w-full my-12">
      <div class="h-px flex-1 bg-blue-900/10"></div>
      <span class="text-[10px] font-black text-blue-900/30 uppercase tracking-widest">OR</span>
      <div class="h-px flex-1 bg-blue-900/10"></div>
    </div>

    <button 
      on:click|stopPropagation={toggleFingerprint}
      class="w-full h-24 rounded-3xl bg-white/50 border-2 border-dashed border-blue-200 flex items-center justify-center gap-4 group active:bg-white transition-colors"
    >
      <img src={fingerprintIcon} alt="Fingerprint" class="w-10 h-10 opacity-80" style="filter: invert(33%) sepia(87%) saturate(1915%) hue-rotate(202deg) brightness(91%) contrast(92%);" />
      <span class="text-blue-900 font-bold uppercase tracking-widest">Use Fingerprint</span>
    </button>

    <div class="mt-16 flex flex-col items-center gap-4">
      <p class="text-blue-900/40 font-bold text-sm">Don't have an account?</p>
      <button on:click={onCreateAccount} class="text-blue-600 font-black uppercase tracking-[0.2em] text-lg hover:underline">
        Create Account
      </button>
    </div>
  </div>

  {#if focusedField}
    <div 
      on:click|stopPropagation
      on:keydown={(e) => e.key === 'Escape' && (focusedField = null)}
      role="dialog"
      aria-label="Virtual Keyboard"
      tabindex="-1" 
      transition:slide={{ axis: 'y', duration: 400 }} 
      class="fixed bottom-0 left-0 right-0 bg-white/95 backdrop-blur-xl border-t border-blue-100 p-6 pb-12 z-40 outline-none"
    >
      <div class="max-w-4xl mx-auto space-y-3">
        <div class="flex justify-center gap-2">
          {#each rows.numbers as num}
            <button 
              type="button"
              on:mousedown|preventDefault={() => handleKeyPress(num)} 
              class="h-14 flex-1 bg-white border border-blue-50 rounded-xl font-bold text-blue-950 shadow-xs active:bg-blue-500 active:text-white transition-colors text-xl"
            >
              {num}
            </button>
          {/each}
        </div>

        {#each rows.letters as row, i}
          <div class="flex justify-center gap-2">
            {#if i === 2}
              <button 
                type="button"
                on:mousedown|preventDefault={() => isCaps = !isCaps} 
                class="w-20 h-16 {isCaps ? 'bg-blue-600 text-white' : 'bg-blue-50 text-blue-600'} border border-blue-100 rounded-xl font-black text-xs"
              >
                CAPS
              </button>
            {/if}

            {#each row as key}
              <button 
                type="button"
                on:mousedown|preventDefault={() => handleKeyPress(key)} 
                class="h-16 flex-1 bg-white border border-blue-50 rounded-xl font-bold text-blue-950 shadow-xs active:bg-blue-500 active:text-white transition-colors text-xl"
              >
                {isCaps ? key : key.toLowerCase()}
              </button>
            {/each}

            {#if i === 2}
              <button 
                type="button"
                on:mousedown|preventDefault={backspace} 
                aria-label="Backspace"
                class="w-20 h-16 bg-blue-50 text-blue-600 border border-blue-100 rounded-xl font-bold flex items-center justify-center"
              >
                ⌫
              </button>
            {/if}
          </div>
        {/each}

        <div class="flex justify-center mt-4 gap-4">
          <button 
            type="button" 
            on:mousedown|preventDefault={() => handleKeyPress('@')} 
            class="w-20 h-14 bg-blue-600 text-white rounded-xl font-black text-xl shadow-lg active:scale-95 transition-transform"
          >
            @
          </button>
          <button 
            type="button" 
            on:mousedown|preventDefault={() => handleKeyPress('.')} 
            class="w-20 h-14 bg-blue-100 text-blue-600 rounded-xl font-black text-2xl active:scale-95 transition-transform"
           >
            .
          </button>

          <button 
            type="button" 
            aria-label="Spacebar" 
            on:mousedown|preventDefault={() => handleKeyPress(' ')} 
            class="{focusedField === 'recoveryEmail' ? 'w-44' : 'w-64'} h-14 bg-white border border-blue-100 rounded-xl active:bg-blue-50 transition-all"
          >
          </button>

          <button 
            type="button" 
            on:click={() => focusedField = null} 
            class="px-12 py-3 bg-blue-950 rounded-full text-[10px] font-black uppercase tracking-[0.4em] text-white shadow-md active:scale-95 transition-transform"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  {/if}

  {#if showFingerprintModal}
    <div 
      transition:fade={{ duration: 200 }}
      class="fixed inset-0 z-50 flex items-center justify-center bg-blue-950/60 backdrop-blur-md p-10"
      on:click|stopPropagation={closeFingerprint}
      role="presentation"
    >
      <div 
        transition:scale={{ start: 0.9, duration: 300 }}
        class="bg-white w-full max-w-sm rounded-[3rem] p-12 flex flex-col items-center text-center shadow-2xl border border-blue-100/20"
        on:click|stopPropagation
        role="presentation"
      >
        <button 
          on:click={simulateScan}
          class="relative w-48 h-48 rounded-full flex items-center justify-center mb-10 transition-all duration-500 overflow-hidden bg-slate-50 border border-blue-50 shadow-inner group"
        >
          {#if scanStatus === 'success'}
            <div class="absolute inset-0 bg-green-500 flex items-center justify-center z-50" in:fade>
              <svg in:scale xmlns="http://www.w3.org/2000/svg" class="w-24 h-24 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
            </div>
          {:else}
            {#if scanStatus === 'scanning'}
              <div 
                class="absolute inset-3 border-[3px] border-slate-200 rounded-full z-10"
              ></div>
              <div 
                class="absolute inset-3 border-[3px] border-transparent border-t-blue-500 rounded-full animate-spin z-20"
                style="transform: rotate(15deg);" 
              ></div>
            {/if}

            <div class="relative w-32 h-32 rounded-full overflow-hidden flex items-center justify-center">
              <img 
                src={fingerprintIcon} 
                alt="Scanning" 
                class="w-20 h-20 z-10 transition-all duration-500 {scanStatus === 'scanning' ? 'opacity-100 scale-105' : 'opacity-20'}" 
                style="filter: {scanStatus === 'scanning' ? 'brightness(0) saturate(100%) invert(48%) sepia(79%) saturate(2500%) hue-rotate(200deg) brightness(100%) contrast(105%)' : 'grayscale(100%)'};"
              />
              
              {#if scanStatus === 'scanning'}
                <div class="absolute inset-0 z-20 pointer-events-none" style="clip-path: circle(50% at 50% 50%);">
                  <div class="w-full h-0.75 bg-blue-400 shadow-[0_0_20px_#3b82f6] animate-[scan_2s_linear_infinite] opacity-0"></div>
                </div>
                
                <div class="absolute inset-0 bg-blue-500/10 animate-pulse z-0"></div>
              {/if}
            </div>
          {/if}
        </button>

        <h3 class="text-3xl font-[1000] uppercase tracking-tighter mb-2 
          {scanStatus === 'success' ? 'text-green-600' : 'text-blue-950'}">
          {#if scanStatus === 'idle'} Tap To Scan
          {:else if scanStatus === 'scanning'} Verifying...
          {:else} Success
          {/if}
        </h3>

        <p class="text-blue-900/40 font-bold text-[10px] uppercase tracking-[0.2em] mb-10">
          HealthSense Biometric Auth
        </p>

        {#if scanStatus !== 'success'}
          <button on:click={closeFingerprint} class="px-6 py-2 rounded-full bg-slate-100 text-slate-400 font-black uppercase text-[10px] tracking-widest active:bg-red-50 active:text-red-400 transition-colors">
            Cancel
          </button>
        {/if}
      </div>
    </div>
  {/if}
</div>

<style>
  @keyframes scan {
    0% { transform: translateY(-10px); opacity: 0; }
    15% { opacity: 1; }
    85% { opacity: 1; }
    100% { transform: translateY(140px); opacity: 0; }
  }
</style>

// HealthSenseWeb2.0/src/pages/Login.tsx
import React, { useState } from "react";
import { FaEye, FaEyeSlash } from "react-icons/fa";
import { useNavigate } from "react-router-dom";
// Import your existing client here
import { supabase } from "../supabaseClient";

const Home: React.FC = () => {
  const navigate = useNavigate();

  // Logic States
  const [showPassword, setShowPassword] = useState<boolean>(false);
  const [emailInput, setEmailInput] = useState<string>(""); 
  const [passwordInput, setPasswordInput] = useState<string>("");
  const [loginError, setLoginError] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);
  // Modal States
  const [showRecoverModal, setShowRecoverModal] = useState(false);
  const [recoveryEmailInput, setRecoveryEmailInput] = useState("");
  const [recoveryLoading, setRecoveryLoading] = useState(false);
  const [recoveryMessage, setRecoveryMessage] = useState({ type: "", text: "" });

  const togglePasswordVisibility = () => setShowPassword(!showPassword);

  const handleLogin = async (e: React.FormEvent) => {
    if (e) e.preventDefault();
    setLoginError("");

    if (!emailInput || !passwordInput) {
      setLoginError("Please enter both credentials.");
      return;
    }

    setIsLoading(true);

    try {
      const userInput = emailInput.toLowerCase().trim();
      let loginEmail = "";

      // 1. LOOKUP: Check if the user exists in your profiles table
      const { data: profile, error: profileError } = await supabase
        .from('profiles')
        .select('recovery_email, username')
        .eq('username', userInput)
        .maybeSingle();

      // Log the error for debugging, but don't stop the flow (allows fallback)
      if (profileError) console.warn("Profile Lookup Error:", profileError.message);

      if (profile) {
        // IF profile exists: use recovery_email if they have one, 
        // otherwise use the kiosk.local fallback
        loginEmail = profile.recovery_email 
          ? profile.recovery_email 
          : `${profile.username}@kiosk.local`;
      } else {
        // IF no profile found by username: maybe they typed their full email or are a .local user?
        loginEmail = userInput.includes("@") 
          ? userInput 
          : `${userInput}@kiosk.local`;
      }

      // 2. AUTHENTICATE: Use the resolved email to sign in
      const { data, error: authError } = await supabase.auth.signInWithPassword({
        email: loginEmail,
        password: passwordInput,
      });

      if (authError) throw authError;

      console.log("Web Portal Login successful:", data.user?.email);
      navigate("/dashboard");

    } catch (err: any) {
      console.error("Auth Error:", err.message);
      // Friendly message for both Patients and Professionals
      setLoginError("Access denied. Please check your credentials.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleRecoverAccount = async () => {
    setRecoveryMessage({ type: "", text: "" });
    const cleanEmail = recoveryEmailInput.trim();

    try {
      setRecoveryLoading(true);

      // 1. Double check the profiles table (This uses the SQL Policy you just fixed!)
      const { data: profile, error: fetchError } = await supabase
        .from("profiles")
        .select("username") 
        .ilike("recovery_email", cleanEmail)
        .maybeSingle();

      if (fetchError) throw fetchError;

      if (!profile) {
        setRecoveryMessage({ 
          type: "error", 
          text: "No account is linked to this recovery email." 
        });
        return;
      }

      // 2. Trigger the reset to the REAL email address
      // This will work ONLY if 'cleanEmail' is the email in the Supabase Auth list
      const { error: resetError } = await supabase.auth.resetPasswordForEmail(cleanEmail, {
        redirectTo: `${window.location.origin}/reset-password`,
      });

      if (resetError) {
        // If this fails, it's usually because the Auth email is actually the @kiosk.local one
        setRecoveryMessage({ 
          type: "error", 
          text: "System could not send to this address. Verify your account setup." 
        });
        return;
      }

      setRecoveryMessage({ 
        type: "success", 
        text: "Success! Reset link sent to your personal inbox." 
      });

    } catch (err: any) {
      setRecoveryMessage({ type: "error", text: "An unexpected error occurred." });
    } finally {
      setRecoveryLoading(false);
    }
  };

  return (
    <div className="min-h-screen w-full flex flex-col bg-[linear-gradient(120deg,#eaf4ff_0%,#cbe5ff_40%,#b0d0ff_70%,#9fc5f8_100%)] font-['Lexend'] overflow-x-hidden relative">
      
      {/* HEADER */}
      <header className="w-full px-8 lg:px-16 py-4 sm:py-6 flex justify-between items-center z-50 shrink-0">
        <div className="flex items-center gap-2">
          <span className="text-xl sm:text-2xl font-black text-[#139dc7] tracking-tighter uppercase">HealthSense</span>
        </div>
        
        <div className="flex items-center gap-2 px-3 py-1.5 bg-white/40 rounded-full border border-white/40 backdrop-blur-md shadow-sm">
          <div className="w-5 h-5 bg-[#139dc7] rounded-full flex items-center justify-center text-[10px] text-white font-black shadow-inner">
            ?
          </div>
          <span className="text-[9px] sm:text-[10px] font-black text-[#139dc7] uppercase tracking-wider">
            Portal Login <span className="opacity-40 ml-1">v2.0</span>
          </span>
        </div>
      </header>

      {/* MAIN CONTENT */}
      <main className="flex-1 flex flex-col items-center justify-center w-full px-6 lg:px-12 mx-auto">
        <div className="flex flex-col lg:flex-row items-center justify-center gap-10 lg:gap-32 w-full max-w-400">

          {/* LEFT SECTION: BRANDING */}
          <div className="text-center lg:text-left flex flex-col items-center lg:items-start gap-1 sm:gap-4 shrink-0">
            <p className="text-[clamp(18px,3.5vw,32px)] font-bold text-[#139dc7] m-0 leading-none opacity-90">
              Welcome to
            </p>
            
            <h1 className="text-[clamp(44px,11vw,120px)] font-black leading-[0.85] m-0 bg-linear-to-r from-[#139dc7] to-[#34A0A4] bg-clip-text text-transparent select-none lg:whitespace-nowrap italic lg:not-italic pr-[0.1em]">
              HealthSense
            </h1>
            
            <p className="text-[clamp(14px,2.2vw,20px)] font-light text-[#139dc7] leading-relaxed max-w-85 lg:max-w-137.5 opacity-70 mt-3 sm:mt-5">
              View your personal health checkup results securely, privately, and conveniently online today.
            </p>
          </div>

          {/* RIGHT SECTION: LOGIN CARD */}
          <div className="w-full max-w-105 sm:max-w-125 shrink-0">
            <div className="relative w-full bg-white/30 backdrop-blur-2xl rounded-[40px] border border-white/50 shadow-[0_30px_100px_rgba(20,60,120,0.1)] flex items-center justify-center p-7 sm:p-14 overflow-hidden">
              
              <div className="absolute -top-[10%] -right-[10%] w-50 h-50 bg-[#139dc7]/15 rounded-full blur-[80px]" />

              <form className="w-full flex flex-col gap-4 sm:gap-7 z-10" onSubmit={handleLogin}>
                
                <div className="text-center space-y-1 sm:space-y-3">
                  <h2 className="text-3xl sm:text-5xl font-normal text-[#139dc7] tracking-tight m-0 pb-1 sm:pb-3">
                    Login
                  </h2>
                  <p className="text-[10px] sm:text-xs font-bold text-[#139dc7]/40 uppercase tracking-[0.3em]">
                    Secure Access
                  </p>
                </div>

                {loginError && (
                  <div className="bg-red-500/10 border border-red-500/20 text-red-600 text-[10px] sm:text-xs py-2 px-3 rounded-xl text-center font-bold">
                    {loginError}
                  </div>
                )}

                {/* Email Input */}
                <div className="space-y-1 sm:space-y-2">
                  <label className="text-[10px] sm:text-xs font-black text-[#139dc7] ml-2 uppercase tracking-widest">Patient ID / Username</label>
                  <input 
                    type="text" 
                    placeholder="firstname.lastname"
                    value={emailInput}
                    onChange={(e) => setEmailInput(e.target.value)}
                    className="w-full h-11 sm:h-16 bg-white/50 border border-white/80 rounded-2xl px-6 text-[#111] placeholder:text-gray-400 focus:bg-white focus:shadow-lg transition-all text-sm sm:text-lg outline-none"
                  />
                </div>

                {/* Password Input */}
                <div className="space-y-1 sm:space-y-2">
                  <label className="text-[10px] sm:text-xs font-black text-[#139dc7] ml-2 uppercase tracking-widest">Password</label>
                  <div className="relative">
                    <input 
                      type={showPassword ? "text" : "password"} 
                      placeholder="••••••••"
                      value={passwordInput}
                      onChange={(e) => setPasswordInput(e.target.value)}
                      className="w-full h-11 sm:h-16 bg-white/50 border border-white/80 rounded-2xl pl-6 pr-14 text-[#111] placeholder:text-gray-400 focus:bg-white focus:shadow-lg transition-all text-sm sm:text-lg outline-none"
                    />
                    <button type="button" onClick={togglePasswordVisibility} className="absolute right-5 top-1/2 -translate-y-1/2 text-gray-400 hover:text-[#139dc7]">
                      {showPassword ? <FaEyeSlash size={18} /> : <FaEye size={18} />}
                    </button>
                  </div>
                </div>

                <button 
                  type="submit"
                  disabled={isLoading}
                  className={`w-full h-12 sm:h-16 rounded-[22px] text-white font-black text-base sm:text-xl shadow-2xl transition-all mt-4 sm:mt-6 uppercase tracking-widest flex items-center justify-center
                    ${isLoading 
                      ? "bg-[#0a4d61] cursor-not-allowed opacity-80" 
                      : "bg-[#139dc7] shadow-blue-300/40 hover:bg-[#0a4d61] hover:-translate-y-1 active:scale-95"
                    }`}
                >
                  {isLoading ? (
                    <div className="flex items-center gap-3">
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      <span>Processing...</span>
                    </div>
                  ) : (
                    "Enter Portal"
                  )}
                </button>

                <div className="flex flex-col items-center gap-3">
                  <button 
                    type="button" 
                    onClick={() => setShowRecoverModal(true)}
                    className="text-[11px] sm:text-sm font-bold text-[#139dc7]/60 hover:text-[#139dc7] transition-all"
                  >
                    Recover Account
                  </button>
                  <p className="text-[9px] text-gray-400 text-center leading-snug">
                    HealthSense Infrastructure v2.0
                  </p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>

      {/* FOOTER */}
      <footer className="w-full py-6 text-center shrink-0">
        <span className="text-[10px] font-black uppercase tracking-[0.4em] text-[#139dc7] opacity-40">
          v2.0 // ArchiveStream Master
        </span>
      </footer>

      {/* RECOVERY MODAL */}
      {showRecoverModal && (
        <div className="fixed inset-0 z-100 flex items-center justify-center p-6 bg-[#001b2e]/60 backdrop-blur-xl animate-in fade-in duration-300">
          <div className="bg-white/95 w-full max-w-md rounded-[40px] shadow-2xl border border-white/50 p-10 relative animate-in zoom-in-95 duration-200">
            <div className="text-center mb-8">
              <h2 className="text-3xl font-black text-[#139dc7] mb-2 uppercase italic tracking-tighter">Recover Access</h2>
              <p className="text-[#139dc7]/60 text-xs font-bold uppercase tracking-widest">Identify your account</p>
            </div>

            <div className="space-y-6">
              <div className="space-y-2">
                <label className="text-[10px] font-black uppercase text-[#139dc7]/40 ml-2 tracking-widest">
                  Recovery Email Address
                </label>
                <div className="relative group">
                  <input 
                    type="email"
                    placeholder="example@email.com"
                    className="w-full h-14 bg-white border border-[#139dc7]/10 rounded-2xl px-5 pr-12 text-[#0a4d61] outline-none focus:border-[#139dc7] focus:ring-4 focus:ring-[#139dc7]/5 transition-all shadow-inner placeholder:text-[#139dc7]/20"
                    /* FIXED NAMES BELOW */
                    value={recoveryEmailInput}
                    onChange={(e) => setRecoveryEmailInput(e.target.value)}
                  />
                  <div className="absolute right-5 top-1/2 -translate-y-1/2 text-[#139dc7]/20 group-focus-within:text-[#139dc7] transition-colors">
                    {/* <FaLanguage size={18} />  */}
                  </div>
                </div>
              </div>

              {recoveryMessage.text && (
                <div className={`text-[11px] font-bold p-4 rounded-2xl border animate-bounce-short ${
                  recoveryMessage.type === "success" 
                    ? "bg-green-50 text-green-600 border-green-100" 
                    : "bg-red-50 text-red-500 border-red-100"
                }`}>
                  {recoveryMessage.type === "success" ? "✓ " : "⚠️ "} {recoveryMessage.text}
                </div>
              )}

              <div className="flex flex-col gap-3">
                <button 
                  onClick={handleRecoverAccount}
                  disabled={recoveryLoading}
                  className="w-full h-14 rounded-2xl font-black bg-[#139dc7] text-white hover:bg-[#0a4d61] shadow-lg shadow-blue-200 transition-all flex items-center justify-center uppercase tracking-widest"
                >
                  {recoveryLoading ? (
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    "Send Reset Link"
                  )}
                </button>
                
                <button 
                  type="button"
                  onClick={() => { 
                    setShowRecoverModal(false); 
                    setRecoveryMessage({ type: "", text: "" }); 
                    setRecoveryEmailInput(""); // Clear input on close
                  }}
                  className="w-full h-12 rounded-2xl font-bold text-[#139dc7]/40 hover:text-[#139dc7] transition-all text-xs uppercase"
                >
                  Back to Login
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;
